keys:
  - &admin-kyle age12zyzprucuah6k35lhk2gk094jnhr6elyckfwnhgkc2hj5rajzays5qrnsz
  - &nixos-desktop age1dj4mg80gntpfue2ch2tdla4jzpe23d3qdc4lup3dtkr8r6a4lsms6zj6fc
  - &nixos-portable age1c4xdxn7eygr0zzek336tdgdmwrjk94cn8l2tlpae3h2fem3759tsdvlzjg
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *nixos-desktop
      - *admin-kyle
      - *nixos-portable

# Adding a new machine
# 
# retrieve the new machine key: `nix-shell -p ssh-to-age --run "cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age"`
# add the new *public key* to `.sops.yaml`(`&nixos-newmachine`: age####)
# from an existing admin machine, run `sops updatekeys secrets/*` so that the secrets are updated with this information
# 
# Adding a new Admin
# create a new admin key with `age-keygen -o ~/.config/sops/age/keys.txt` and retrieve its public key with `age-keygen -y ~/.config/sops/age/keys.txt`
# add the admin *public key* to `.sops.yaml`(`&admin-new`: age####), then you can run admin commands such as `sops updatekeys secrets/*`
#
# Reusing the same Admin
# copy `~/.config/sops/age/keys.txt` if the same admin identity is needed on another machine
